export enum YouTubeCategory {
  FILM_ANIMATION = "1",
  AUTOS_VEHICLES = "2",
  MUSIC = "10",
  PETS_ANIMALS = "15",
  SPORTS = "17",
  TRAVEL_EVENTS = "19",
  GAMING = "20",
  BLOGS = "22",
  COMEDY = "23",
  ENTERTAINMENT = "24",
  NEWS_POLITICS = "25",
  HOWTO_STYLE = "26",
  EDUCATION = "27",
  SCIENCE_TECH = "28",
  NONPROFITS_ACTIVISM = "29",
}

export const YOUTUBE_CATEGORY_MAP: Record<YouTubeCategory, string> = {
  [YouTubeCategory.FILM_ANIMATION]: "영화 및 애니메이션",
  [YouTubeCategory.AUTOS_VEHICLES]: "자동차 및 차량",
  [YouTubeCategory.MUSIC]: "음악",
  [YouTubeCategory.PETS_ANIMALS]: "애완동물 및 동물",
  [YouTubeCategory.SPORTS]: "스포츠",
  [YouTubeCategory.TRAVEL_EVENTS]: "여행 및 이벤트",
  [YouTubeCategory.GAMING]: "게임",
  [YouTubeCategory.BLOGS]: "블로그",
  [YouTubeCategory.COMEDY]: "코미디",
  [YouTubeCategory.ENTERTAINMENT]: "엔터테인먼트",
  [YouTubeCategory.NEWS_POLITICS]: "뉴스 및 정치",
  [YouTubeCategory.HOWTO_STYLE]: "노하우 및 스타일",
  [YouTubeCategory.EDUCATION]: "교육",
  [YouTubeCategory.SCIENCE_TECH]: "과학 및 기술",
  [YouTubeCategory.NONPROFITS_ACTIVISM]: "비영리 및 사회운동",
};
